ads/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
    path('ad/game',
        views.GamePlay, name='game'),
]

autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

cats/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'cats'
urlpatterns = [
    path('', views.CatList.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedList.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

crispy/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name='crispy'
urlpatterns = [
    path('', TemplateView.as_view(template_name='crispy/main.html'), name="main"),
    path('boring', views.MyView.as_view(template_name='crispy/boring.html')),
    path('awesome', views.MyView.as_view(template_name='crispy/awesome.html')),
]

menu/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name='menu'
urlpatterns = [
    path('', TemplateView.as_view(template_name='menu/main_menu.html'), name='main'),
    path('page1', TemplateView.as_view(template_name='menu/main_menu.html'), name='page1'),
    path('page2', TemplateView.as_view(template_name='menu/main_menu.html'), name='page2'),
    path('page3', TemplateView.as_view(template_name='menu/main_menu.html'), name='page3'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    path('ads/', include('ads.urls')),
    path('pics/', include('pics.urls')),
    path('crispy/', include('crispy.urls')),
    path('autos/', include('autos.urls')),
    path('myarts/', include('myarts.urls')),
    path('cats/', include('cats.urls')),
    path('polls/', include('polls.urls')),
    path('forums/', include('forums.urls')),
    path('chat/', include('chat.urls')),
    path('favs/', include('favs.urls')),

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('owner', views.owner, name='owner'),
]

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.views import View

# Create your views here.

menu/templates/menu/base_menu.html
<head>
<meta name="dj4e" content="6ad4ba33df5bd3abe7bac00c420c5b6c">
</head>

{% extends 'base_bootstrap.html' %}
{% load app_tags %} <!-- see home/templatetags/app_tags.py and dj4e-samples/settings.py -->
{% block navbar %}
<!-- https://www.w3schools.com/bootstrap/bootstrap_navbar.asp -->
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'menu:main' %}">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">

      <!-- Assign output of url function to a variable named
          'xyz' to use in the if statement -->
      {% url 'home' as xyz %}
      <li {% if request.get_full_path == xyz %}class="active"{% endif %}>
          <a href="/">Home</a></li>

      {% url 'menu:page1' as abc1 %}
      <li {% if request.get_full_path == abc1 %}class="active"{% endif %}>
          <a href="/admin">Admin page</a></li>

      {% url 'polls:index' as abc2 %}
      <li {% if request.get_full_path == abc2 %}class="active"{% endif %}>
          <a href="{% url 'polls:index' %}">Polls App</a></li>

      <li class="dropdown">
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">Forms
          <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'autos:all' %}">Autos CRUD</a></li>
            <li><a href="{% url 'cats:all' %}">Cats CRUD</a></li>
            <li><a href="{% url 'crispy:main' %}">Crispy Form</a></li>
        </ul>
       </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
      <!-- gravatar depends on app_tags being loaded -->
      <!-- https://brobin.me/blog/2016/07/super-simple-django-gravatar/ -->
      <a href="#" data-toggle="dropdown" class="dropdown-toggle">
        <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'logout' %}?next={% url 'menu:main' %}">Logout</a></li>
        </ul>
       </li>
       {% else %}
       <li><a href="{% url 'login' %}?next={% url 'menu:main' %}">Login</a></li>
       {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

menu/templates/menu/main_menu.html
<head>
<meta name="dj4e" content="6ad4ba33df5bd3abe7bac00c420c5b6c">
</head>

{% extends 'menu/base_menu.html' %}
{% block title %}{{ settings.APP_NAME }}{% endblock %}
{% block content %}
<h4>I am the content block in templates/menu/main_menu.html</h4>
<p>
This is your current path : {{ request.path }}
</p>
<p>
If you are lost, head back to the <a href="/">main page</a> or click Home.
</p>
{% endblock %}